version: "3.8"
name: docdoc-container
services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: docdoc-database
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: docdoc_database

volumes:
  postgres_data:
    driver: local
